---
language: node_js

node_js:
  - "5"

sudo: false

cache:
  directories:
    - node_modules

env:
  - EMBER_TRY_SCENARIO=ember-2.5
  - EMBER_TRY_SCENARIO=ember-2.6
  - EMBER_TRY_SCENARIO=ember-release
  - ALLOW_DEPRECATIONS=true EMBER_TRY_SCENARIO=ember-beta
  - ALLOW_DEPRECATIONS=true EMBER_TRY_SCENARIO=ember-canary

matrix:
  fast_finish: true
  allow_failures:
    - env: ALLOW_DEPRECATIONS=true EMBER_TRY_SCENARIO=ember-beta
    - env: ALLOW_DEPRECATIONS=true EMBER_TRY_SCENARIO=ember-canary

before_install:
  - npm config set spin false
  - npm install -g bower
  - npm install phantomjs-prebuilt

install:
  - npm install -g bower
  - npm install
  - bower install

script:
  - ember try:one $EMBER_TRY_SCENARIO test --skip-cleanup

# after_script:
#   - sed -i -- 's/SF:ember-cli-materialize\/\(.*\)/SF:addon\/\1.js/' lcov.dat
#   - cat lcov.dat | coveralls

after_success:
# Remove the downloaded copy of phantomJS
- rm -rf travis-phantomjs
# Add a remote, authenticating via an OAuth token (encrypted via "travis secure")
- git remote add deploy https://$GH_TOKEN:x-oauth-basic@github.com/mike-north/ember-cli-materialize.git
# Download all branches from this new remote (really the same remote, but different auth)
- git fetch deploy
# Check out a local copy of "master", but don't switch to it yet
- git branch $GH_DEST_BRANCH deploy/$GH_DEST_BRANCH
# Set up some required git config stuff (more env variables encrypted via "travis secure")
- git config user.name $GIT_NAME
- git config user.email $GIT_EMAIL
# Generate the github pages. When this command is finished I'll be on "master" branch with a
# new commit already made (but not pushed)
# Push the new commit
- /bin/bash lib/try-generate-pages.sh
- git checkout master
